### ISSUE TITLE
Question about recommendations 

### ISSUE THREAD

**Issue by PaddyCube** [AlessioMorale/ld06_lidar#9]
Hello,
as there are mostly no information or reviews available to this tiny device I ask you to share your toughts. Is this a valuable device and are you satisfied so far?

**Comment by AlessioMorale** [comment]
I have not yet mounted it to any robot but I managed to do some testing.
The device seems to work well, from a characteristics point of view is similar to YDLidar X4 or RPLidar A1. 
The main advantage (and possibly the feature that would justify the price difference) is the size, it is way smaller and sell contained that the former twos.
An additional plus is the TOF technology used compared to triangulation of the other devices and the more quiet direct drive operation vs belt.
I would say, if size is an issue I would go with the 38x38mm of the LD06, otherwise you can go with RPLidar or YDLidar that are a lot cheaper (and the software provided is a lot better).

**Comment by PaddyCube** [comment]
Thank you Alessio for your thoughts,
Meanwhile I found one at Amazon for the same price as for a RPLidar A1 and received it today. This device is really incredible small, hopefully I will not swallow it.
The device I received is self-contained but not at the bottom where it is open. Is this true to your too? Might become an issue when mounting on a robot and using it outdoors.

**Comment by AlessioMorale** [comment]
Unfortunately this version is not splash/water proof. I know they have a kickstarter for a model that add this feature.
Bottom for LD06 is open. As a quick and dirt hack I would suggest printing a base "gasket" in tpu and applying some sort of sugru like stuff to the connector port.
